# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: main

  - package-ecosystem: "npm"
    directory: "/src/UI/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: main

  - package-ecosystem: "docker"
    directory: "/src/Api/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: main
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "
