name: Registry Cleaner

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

env:
  PR_NUMBER: ${{ github.event.number || -1 }}

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Merge Notice
        if: ${{ github.event.pull_request.merged }}
        run: echo "PR-${{ env.PR_NUMBER }} was merged"
      
      # https://github.com/camargo/delete-untagged-action
      - name: Clean untagged images
        uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          personal-account: true
          package-name: weather-api
